export const jobPostList = [
  {
    id: "01",
    job_name: "DUBAI, UAE",
    time: "Проект",
    location: "Trump International Hotel & Tower",
    date_line: "Люксовый отель и резиденции",
    level: "Статус: В реализации",
    salary: {
      range: "В партнерстве с Trump Org.",
      time: "year",
    },
    link: "job-details",
  },
  {
    id: "02",
    job_name: "DOHA, QATAR",
    time: "Проект",
    location: "Les Vagues by Elie Saab",
    date_line: "Дизайн от Elie Saab",
    level: "Статус: Завершен",
    salary: {
      range: "Вид на залив, эксклюзив",
      time: "month",
    },
    link: "job-details",
  },
  {
    id: "03",
    job_name: "MARBELLA, SPAIN",
    time: "Проект",
    location: "Tierra Viva by Lamborghini",
    date_line: "Виллы с дизайном ",
    level: "Статус: В реализации",
    salary: {
      range: "Панорамные виды",
      time: "week",
    },
    link: "job-details",
  },
  {
    id: "04",
    job_name: "RIYADH, KSA",
    time: "Проект",
    location: "Neptune by Mouawad",
    date_line: "Дизайн от Mouawad",
    level: "Статус: В реализации",
    salary: {
      range: "Роскошные виллы",
      time: "month",
    },
    link: "job-details",
  },
  {
    id: "05",
    job_name: "LONDON, UK",
    time: "Проект",
    location: "The Mulliner",
    date_line: "Историческое здание, люкс",
    level: "Статус: Завершен",
    salary: {
      range: "Рядом с Green Park",
      time: "hour",
    },
    link: "job-details",
  },
];
