export const jobPostList = [
  {
    id: "01",
    time: "Project",
    job_name: "Saudi Arabia",
    location: "TRUMP TOWER JEDDAH",
    date_line: "December 2029",
    level: "Jeddah Corniche, Saudi Arabia",
    salary: {
      range: "Seafront Residences",
      time: "year",
    },
    link: "#",
  },
  {
    id: "02",
    time: "Project",
    job_name: "UAE",
    location: "TRUMP INTERNATIONAL HOTEL & TOWER DUBAI",
    date_line: "December 2031",
    level: "Dubai",
    salary: {
      range: "Branded Hotel & Residential Tower",
      time: "year",
    },
    link: "#",
  },
  {
    id: "03",
    time: "Project",
    job_name: "QATAR",
    location: "LES VAGUES BY ELIE SAAB",
    date_line: "December 2027",
    level: "",
    salary: {
      range: "Branded Residential Complex",
      time: "year",
    },
    link: "#",
  },
  {
    id: "04",
    time: "Project",
    job_name: "Oman",
    location: "TRUMP INTERNATIONAL HOTEL, OMAN",
    date_line: "December 2028 muscat",
    level: "",
    salary: {
      range: "HOTEL",
      time: "year",
    },
    link: "#",
  },
  {
    id: "05",
    time: "Project",
    job_name: "Oman",
    location: "TRUMP CLIFF VILLAS",
    date_line: "December 2028 muscat",
    level: "",
    salary: {
      range: "Furnished Residences",
      time: "year",
    },
    link: "#",
  },
  {
    id: "06",
    time: "Project",
    job_name: "Oman",
    location: "TRUMP GOLF VILLAS",
    date_line: "December 2028 muscat",
    level: "",
    salary: {
      range: "Mixed-use Development",
      time: "year",
    },
    link: "#",
  },
  {
    id: "07",
    time: "Project",
    job_name: "Oman",
    location: "FAIRWAY VILLAS",
    date_line: "December 2028 muscat",
    level: "",
    salary: {
      range: "Villa",
      time: "year",
    },
    link: "#",
  },
  {
    id: "08",
    time: "Project",
    job_name: "Oman",
    location: "THE GREAT ESCAPE",
    date_line: "December 2029 muscat",
    level: "",
    salary: {
      range: "Unfurnished apartments",
      time: "year",
    },
    link: "#",
  },
  {
    id: "09",
    time: "Project",
    job_name: "Oman",
    location: "THE GREAT ESCAPE 2",
    date_line: "December 2029 muscat",
    level: "",
    salary: {
      range: "Unfurnished apartments",
      time: "year",
    },
    link: "#",
  },
  {
    id: "10",
    time: "Project",
    job_name: "Oman",
    location: "COASTAL INVESTMENT VILLAS ",
    date_line: "December 2027 muscat",
    level: "",
    salary: {
      range: "Villa",
      time: "year",
    },
    link: "#",
  },
  {
    id: "11",
    time: "Project",
    job_name: "Oman",
    location: "SUNRISE HAVEN",
    date_line: "December 2027 muscat",
    level: "",
    salary: {
      range: "Fully Furnished 3BR",
      time: "year",
    },
    link: "#",
  },
  {
    id: "12",
    time: "Project",
    job_name: "Oman",
    location: "AMOUR SANS DETOUR",
    date_line: "December 2029",
    level: "",
    salary: {
      range: "3 Bedroom Villas muscat",
      time: "year",
    },
    link: "#",
  },
 
];
